create table "public"."conversations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "conversationId" text,
    "message" text
);


alter table "public"."conversations" enable row level security;

CREATE UNIQUE INDEX conversations_pkey ON public.conversations USING btree (id);

alter table "public"."conversations" add constraint "conversations_pkey" PRIMARY KEY using index "conversations_pkey";