create table "public"."unanswered_questions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "query" text not null
);


alter table "public"."unanswered_questions" enable row level security;

CREATE UNIQUE INDEX unanswered_questions_pkey ON public.unanswered_questions USING btree (id);

alter table "public"."unanswered_questions" add constraint "unanswered_questions_pkey" PRIMARY KEY using index "unanswered_questions_pkey";

create policy "Enable insert for all users"
on "public"."unanswered_questions"
as permissive
for insert
to public
with check (true);



